#!/usr/bin/env python3
"""
Borough data for pSEO generation.
Each entry contains planning-specific local context that makes pSEO pages
non-duplicative and actually useful for SEO/AEO/GEO.
"""

BOROUGHS = {
    "camden": {
        "name": "Camden",
        "council": "London Borough of Camden",
        "planning_authority": "Camden Council",
        "postcodes": "NW1, NW3, NW5, NW6, WC1, WC1H, WC1N, WC1R, WC1V, WC1X, N6, N7, N19",
        "population": 270_000,
        "article_4": True,
        "article_4_notes": "Article 4 removes permitted development for HMO conversions (C3 to C4) across the borough, plus restrictions on basement extensions in 12 conservation areas.",
        "conservation_areas": 40,
        "notable_conservation": "Hampstead, Primrose Hill, Bloomsbury, Camden Town, Fitzrovia",
        "typical_housing": "Victorian and Edwardian terraces, Georgian townhouses in Bloomsbury and Hampstead, post-war mansion blocks, modern developments in King's Cross.",
        "character": "Creative, affluent in Hampstead and Primrose Hill; dense mixed-use around Camden Town and Kings Cross; academic character in Bloomsbury.",
        "adjacent": ["westminster", "islington", "barnet", "haringey", "brent", "city-of-london"],
        "basement_policy": True,
        "basement_notes": "Camden's basement policy (Policy A5) restricts single-storey basements to 50% of garden area; double-storey basements generally refused outside commercial zones.",
    },
    "islington": {
        "name": "Islington",
        "council": "London Borough of Islington",
        "planning_authority": "Islington Council",
        "postcodes": "N1, N4, N5, N7, N19, EC1",
        "population": 216_000,
        "article_4": True,
        "article_4_notes": "Article 4 Direction covering the whole borough removes permitted development rights for HMO conversions (C3 to C4). Separate Article 4 for office-to-residential in key areas.",
        "conservation_areas": 40,
        "notable_conservation": "Barnsbury, Canonbury, Highbury, Clerkenwell, Angel",
        "typical_housing": "Georgian and early Victorian terraces, Victorian bye-law housing, 1930s mansion blocks, converted industrial buildings in Clerkenwell and Farringdon.",
        "character": "Densely terraced, gentrified; strong conservation area coverage; active planning department.",
        "adjacent": ["camden", "hackney", "haringey", "city-of-london"],
        "basement_policy": False,
    },
    "hackney": {
        "name": "Hackney",
        "council": "London Borough of Hackney",
        "planning_authority": "Hackney Council",
        "postcodes": "E2, E5, E8, E9, N1, N4, N5, N16",
        "population": 281_000,
        "article_4": True,
        "article_4_notes": "Article 4 Direction covers HMO conversions borough-wide and office-to-residential in specific commercial zones.",
        "conservation_areas": 29,
        "notable_conservation": "De Beauvoir Town, Stoke Newington, Dalston Lane, Hackney Central, Clapton",
        "typical_housing": "Victorian terraces dominate; large post-war estates around Hackney Wick; Georgian fragments in De Beauvoir and Stoke Newington; new-build around the Olympic Park.",
        "character": "Young demographic; high design-quality bar in planning; mansards routinely approved in rear-of-terrace positions within conservation areas following the Hackney design guide.",
        "adjacent": ["islington", "haringey", "waltham-forest", "newham", "tower-hamlets", "city-of-london"],
        "basement_policy": False,
    },
    "westminster": {
        "name": "Westminster",
        "council": "City of Westminster",
        "planning_authority": "Westminster City Council",
        "postcodes": "SW1, W1, W2, W9, NW1, NW8, WC2",
        "population": 205_000,
        "article_4": True,
        "article_4_notes": "Multiple Article 4 Directions — office-to-residential restrictions, HMO conversions, retail to residential in shopping zones.",
        "conservation_areas": 56,
        "notable_conservation": "Mayfair, Belgravia, Marylebone, Pimlico, Soho, Covent Garden, St John's Wood",
        "typical_housing": "Grand Georgian and Regency terraces in Belgravia and Pimlico; Victorian and Edwardian mansion blocks; heritage-rich townhouses throughout; very high listed building density.",
        "character": "Heritage-first planning approach; listed buildings on almost every street; basement and rear extension policies particularly strict.",
        "adjacent": ["camden", "kensington-and-chelsea", "wandsworth", "lambeth", "city-of-london"],
        "basement_policy": True,
        "basement_notes": "Westminster basement policy restricts to single-storey, typically under 50% of rear garden footprint; lightwells and rooflights strictly controlled in conservation areas.",
    },
    "kensington-and-chelsea": {
        "name": "Kensington and Chelsea",
        "council": "Royal Borough of Kensington and Chelsea",
        "planning_authority": "RBKC Planning",
        "postcodes": "SW1, SW3, SW5, SW7, SW10, W8, W10, W11, W14",
        "population": 143_000,
        "article_4": True,
        "article_4_notes": "Article 4 Directions covering HMOs, office-to-residential, and basement developments — RBKC has some of the strictest basement policies in London.",
        "conservation_areas": 38,
        "notable_conservation": "Kensington, Chelsea, Notting Hill, Holland Park, Earls Court",
        "typical_housing": "Grand white stucco Regency and Victorian terraces; red-brick Queen Anne mansions in Kensington; Edwardian mansion blocks; almost no post-war housing stock.",
        "character": "Internationally wealthy residents; extensive listed building coverage; heritage and streetscape prioritised in every decision.",
        "adjacent": ["westminster", "hammersmith-and-fulham", "brent"],
        "basement_policy": True,
        "basement_notes": "RBKC's basement policy (post-2015) limits to single-storey under 50% of garden area; double-storey basements effectively prohibited in residential streets.",
    },
    "hammersmith-and-fulham": {
        "name": "Hammersmith and Fulham",
        "council": "London Borough of Hammersmith and Fulham",
        "planning_authority": "Hammersmith & Fulham Council",
        "postcodes": "W6, W12, W14, SW6, SW10",
        "population": 184_000,
        "article_4": True,
        "article_4_notes": "Article 4 removes PD for HMO conversions; restrictions on ground-floor shop-to-residential in certain streets.",
        "conservation_areas": 45,
        "notable_conservation": "Hammersmith Grove, Brackenbury Village, Fulham Palace Road, Parsons Green, Walham Green",
        "typical_housing": "Victorian and Edwardian terraces — particularly two-storey bay-fronted terraces south of the river in Fulham and Parsons Green; mansion blocks along main roads.",
        "character": "Suburban-feel residential streets with strong conservation area coverage; well-established mansard precedents on many terraces.",
        "adjacent": ["kensington-and-chelsea", "brent", "ealing", "hounslow", "richmond-upon-thames", "wandsworth"],
        "basement_policy": False,
    },
    "wandsworth": {
        "name": "Wandsworth",
        "council": "London Borough of Wandsworth",
        "planning_authority": "Wandsworth Council",
        "postcodes": "SW8, SW11, SW12, SW15, SW17, SW18, SW19",
        "population": 329_000,
        "article_4": True,
        "article_4_notes": "Article 4 for HMO conversions covering the whole borough.",
        "conservation_areas": 45,
        "notable_conservation": "Wandsworth Common, Clapham Common West, Tonsley, Magdalen Park, Nightingale Triangle",
        "typical_housing": "Extensive Victorian terraced streets — the classic London side-return extension opportunity; Edwardian villas around the commons; 1930s semi-detached in Southfields.",
        "character": "Family-oriented, high side-return extension and loft conversion rates; planning department experienced with Victorian terrace modifications.",
        "adjacent": ["lambeth", "merton", "kingston-upon-thames", "richmond-upon-thames", "hammersmith-and-fulham", "westminster"],
        "basement_policy": False,
    },
    "lambeth": {
        "name": "Lambeth",
        "council": "London Borough of Lambeth",
        "planning_authority": "Lambeth Council",
        "postcodes": "SE1, SE11, SE24, SE27, SW2, SW4, SW8, SW9, SW16",
        "population": 318_000,
        "article_4": True,
        "article_4_notes": "Borough-wide Article 4 for HMO conversions; plus office-to-residential restrictions.",
        "conservation_areas": 64,
        "notable_conservation": "Clapham Common, Herne Hill, Brixton Road, Kennington, Brockwell Park, Streatham Hill",
        "typical_housing": "Victorian terraces in Clapham, Brixton, Herne Hill; Edwardian villas; 1930s and post-war estates in parts of Streatham; Georgian in Kennington.",
        "character": "Mix of dense Victorian residential and post-war estate; strong conservation area coverage; generally design-led planning decisions.",
        "adjacent": ["southwark", "wandsworth", "croydon", "merton", "westminster"],
        "basement_policy": False,
    },
    "southwark": {
        "name": "Southwark",
        "council": "London Borough of Southwark",
        "planning_authority": "Southwark Council",
        "postcodes": "SE1, SE5, SE15, SE16, SE17, SE21, SE22",
        "population": 318_000,
        "article_4": True,
        "article_4_notes": "Article 4 for HMOs borough-wide; additional Article 4 for office-to-residential in Bermondsey and Elephant & Castle.",
        "conservation_areas": 43,
        "notable_conservation": "Camberwell Grove, Bermondsey Street, Dulwich Village, Peckham Rye, Borough",
        "typical_housing": "Georgian and Regency in Bermondsey and Borough; Victorian terraces in Camberwell and Peckham; Dulwich Estate controlled housing; riverside new-build.",
        "character": "Dulwich Estate private planning scheme affects much of SE21 and SE22; Southwark planning for rest of borough; strong heritage context.",
        "adjacent": ["lambeth", "lewisham", "bromley", "tower-hamlets", "city-of-london"],
        "basement_policy": False,
    },
    "lewisham": {
        "name": "Lewisham",
        "council": "London Borough of Lewisham",
        "planning_authority": "Lewisham Council",
        "postcodes": "SE3, SE4, SE6, SE8, SE12, SE13, SE14, SE23, SE26",
        "population": 302_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 30,
        "notable_conservation": "Blackheath, Deptford High Street, Forest Hill, Hither Green, Lee Green",
        "typical_housing": "Victorian and Edwardian terraces across Brockley, Honor Oak, Forest Hill; 1930s semi-detached in Catford and Hither Green; post-war mixed in Deptford.",
        "character": "Generally permissive planning compared to central boroughs; loft conversions and side-return extensions routinely approved under PD.",
        "adjacent": ["southwark", "greenwich", "bromley", "tower-hamlets"],
        "basement_policy": False,
    },
    "greenwich": {
        "name": "Greenwich",
        "council": "Royal Borough of Greenwich",
        "planning_authority": "Greenwich Council",
        "postcodes": "SE3, SE7, SE9, SE10, SE18, SE28",
        "population": 287_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 20,
        "notable_conservation": "Greenwich Town Centre (World Heritage Site), Blackheath, Charlton, Eltham Park",
        "typical_housing": "Georgian in Greenwich town centre; Victorian terraces in East Greenwich, Charlton; inter-war semi-detached in Eltham; new-build along the riverside.",
        "character": "World Heritage Site status in Greenwich town centre adds heritage weight; outer borough areas (Eltham, Thamesmead) generally permissive.",
        "adjacent": ["lewisham", "bexley", "bromley", "newham", "tower-hamlets"],
        "basement_policy": False,
    },
    "tower-hamlets": {
        "name": "Tower Hamlets",
        "council": "London Borough of Tower Hamlets",
        "planning_authority": "Tower Hamlets Council",
        "postcodes": "E1, E2, E3, E14",
        "population": 324_000,
        "article_4": True,
        "article_4_notes": "Article 4 for HMOs borough-wide; additional Article 4 covering office-to-residential in Canary Wharf and City Fringe.",
        "conservation_areas": 58,
        "notable_conservation": "Spitalfields, Whitechapel Market, Fournier Street, Tredegar Square, Wapping Pierhead",
        "typical_housing": "Georgian in Spitalfields and Wapping; Victorian industrial conversions; extensive post-war social housing; modern high-density towers in Canary Wharf and Aldgate.",
        "character": "High heritage value in pockets (Spitalfields, Wapping), mixed with substantial regeneration areas; active planning committee.",
        "adjacent": ["hackney", "newham", "city-of-london", "southwark", "greenwich"],
        "basement_policy": False,
    },
    "barnet": {
        "name": "Barnet",
        "council": "London Borough of Barnet",
        "planning_authority": "Barnet Council",
        "postcodes": "N2, N3, N10, N11, N12, N14, N20, NW2, NW4, NW7, NW9, NW11, EN4, EN5",
        "population": 389_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 20,
        "notable_conservation": "Hampstead Garden Suburb, Mill Hill, Hendon, Golders Green, Monken Hadley",
        "typical_housing": "1930s semi-detached dominates; Edwardian villas in Muswell Hill, Finchley; Garden Suburb Arts & Crafts in Hampstead Garden Suburb; post-war flats in Colindale.",
        "character": "Suburban outer-London borough; permitted development used heavily; Hampstead Garden Suburb has its own residents' trust with additional design controls.",
        "adjacent": ["harrow", "brent", "camden", "haringey", "enfield"],
        "basement_policy": False,
    },
    "haringey": {
        "name": "Haringey",
        "council": "London Borough of Haringey",
        "planning_authority": "Haringey Council",
        "postcodes": "N4, N6, N8, N10, N15, N17, N22",
        "population": 264_000,
        "article_4": True,
        "article_4_notes": "Borough-wide Article 4 for HMO conversions.",
        "conservation_areas": 29,
        "notable_conservation": "Highgate Village, Muswell Hill, Crouch End, Tottenham Green, Bruce Castle",
        "typical_housing": "Edwardian terraces in Crouch End, Muswell Hill; Victorian two-up-two-downs in Harringay Ladder; 1930s semi-detached in Muswell Hill; post-war in Tottenham.",
        "character": "Muswell Hill and Crouch End have strong conservation coverage with clear loft/mansard precedents; Tottenham generally permissive.",
        "adjacent": ["barnet", "enfield", "waltham-forest", "hackney", "islington", "camden"],
        "basement_policy": False,
    },
    "waltham-forest": {
        "name": "Waltham Forest",
        "council": "London Borough of Waltham Forest",
        "planning_authority": "Waltham Forest Council",
        "postcodes": "E4, E10, E11, E17",
        "population": 278_000,
        "article_4": True,
        "article_4_notes": "Article 4 for HMO conversions in key residential streets.",
        "conservation_areas": 17,
        "notable_conservation": "Walthamstow Village, Lloyd Park, Leyton, Highams Park",
        "typical_housing": "Victorian terraces across Walthamstow, Leyton and Leytonstone; 1930s semi-detached in Chingford and Highams Park; post-war flats around Walthamstow Central.",
        "character": "Walthamstow Village is a designated conservation area with tight design controls; rest of borough is generally permissive with active side-return extension approvals.",
        "adjacent": ["haringey", "enfield", "redbridge", "newham", "hackney"],
        "basement_policy": False,
    },
    "redbridge": {
        "name": "Redbridge",
        "council": "London Borough of Redbridge",
        "planning_authority": "Redbridge Council",
        "postcodes": "E11, E12, E18, IG1, IG2, IG3, IG4, IG5, IG6, IG7, IG8",
        "population": 313_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 14,
        "notable_conservation": "Wanstead Village, Snaresbrook, Aldersbrook, Woodford Green",
        "typical_housing": "1930s semi-detached dominates outer Redbridge; Edwardian terraces and villas in Wanstead and South Woodford; post-war estates in Ilford central.",
        "character": "Outer London suburban; permitted development used heavily for loft conversions and single-storey rear extensions.",
        "adjacent": ["waltham-forest", "havering", "barking-and-dagenham", "newham"],
        "basement_policy": False,
    },
    "newham": {
        "name": "Newham",
        "council": "London Borough of Newham",
        "planning_authority": "Newham Council",
        "postcodes": "E6, E7, E12, E13, E15, E16",
        "population": 353_000,
        "article_4": True,
        "article_4_notes": "Article 4 Direction requires planning permission for any HMO conversion, plus restrictions on office-to-residential in Stratford and Royal Docks.",
        "conservation_areas": 10,
        "notable_conservation": "Manor Park, Forest Gate, Plaistow, West Ham",
        "typical_housing": "Victorian terraces across West Ham, Forest Gate, Plaistow; Olympic-era new-build in Stratford; post-war in Canning Town; substantial ongoing regeneration.",
        "character": "High-regeneration borough; Olympic Park and Royal Docks drive major development; heavily HMO-managed borough.",
        "adjacent": ["tower-hamlets", "hackney", "waltham-forest", "redbridge", "barking-and-dagenham", "greenwich"],
        "basement_policy": False,
    },
    "ealing": {
        "name": "Ealing",
        "council": "London Borough of Ealing",
        "planning_authority": "Ealing Council",
        "postcodes": "W3, W5, W7, W13, UB1, UB2, UB5, UB6, NW10",
        "population": 342_000,
        "article_4": True,
        "article_4_notes": "Article 4 for HMOs in specific streets in Acton, Ealing and Southall.",
        "conservation_areas": 30,
        "notable_conservation": "Ealing Broadway, Pitshanger, Bedford Park, Acton Green, Hanwell",
        "typical_housing": "Victorian and Edwardian villas in Ealing central; 1930s semi-detached in Northolt and Hanwell; mansion blocks along main roads; Bedford Park is a listed Arts & Crafts garden suburb.",
        "character": "Leafy outer-west London; Bedford Park conservation area has strict heritage controls; rest of borough generally permissive.",
        "adjacent": ["hounslow", "hillingdon", "brent", "hammersmith-and-fulham"],
        "basement_policy": False,
    },
    "hounslow": {
        "name": "Hounslow",
        "council": "London Borough of Hounslow",
        "planning_authority": "Hounslow Council",
        "postcodes": "W3, W4, TW3, TW4, TW5, TW7, TW8, TW13, TW14",
        "population": 288_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 30,
        "notable_conservation": "Chiswick, Bedford Park, Old Isleworth, Brentford",
        "typical_housing": "Edwardian villas in Chiswick and Turnham Green; Georgian in Isleworth; 1930s semi-detached in Hounslow and Feltham; riverside new-build in Brentford.",
        "character": "Chiswick is one of west London's most conservation-controlled areas; outer Hounslow is permissive suburban.",
        "adjacent": ["hillingdon", "ealing", "hammersmith-and-fulham", "richmond-upon-thames"],
        "basement_policy": False,
    },
    "richmond-upon-thames": {
        "name": "Richmond upon Thames",
        "council": "London Borough of Richmond upon Thames",
        "planning_authority": "Richmond Council",
        "postcodes": "SW13, SW14, TW1, TW2, TW9, TW10, TW11, TW12",
        "population": 197_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 72,
        "notable_conservation": "Richmond Green, Kew Green, Hampton Wick, Twickenham Riverside, Barnes Village, Ham Common",
        "typical_housing": "Georgian in Richmond Green and Twickenham; Edwardian villas in Barnes and East Sheen; 1930s semi-detached in Whitton; riverside cottages along the Thames.",
        "character": "Highest conservation area coverage in London; Royal Parks and Thames corridor add heritage layers; design quality heavily scrutinised.",
        "adjacent": ["hounslow", "kingston-upon-thames", "wandsworth", "hammersmith-and-fulham"],
        "basement_policy": False,
    },
    "kingston-upon-thames": {
        "name": "Kingston upon Thames",
        "council": "Royal Borough of Kingston upon Thames",
        "planning_authority": "Kingston Council",
        "postcodes": "KT1, KT2, KT3, KT5, KT6, KT9, SW15, SW19, SW20",
        "population": 177_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 22,
        "notable_conservation": "Kingston Old Town, Surbiton, Hampton Wick, Coombe Hill",
        "typical_housing": "Edwardian villas in Surbiton and New Malden; Victorian terraces in Kingston central; 1930s semi-detached in Chessington and Tolworth; post-war in New Malden.",
        "character": "Outer south-west London suburban; generally permissive; riverside conservation areas add character in Kingston town.",
        "adjacent": ["richmond-upon-thames", "merton", "sutton"],
        "basement_policy": False,
    },
    "merton": {
        "name": "Merton",
        "council": "London Borough of Merton",
        "planning_authority": "Merton Council",
        "postcodes": "SW16, SW17, SW19, SW20, CR4",
        "population": 215_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 28,
        "notable_conservation": "Wimbledon Village, John Innes, Mitcham Cricket Green, Wimbledon Common",
        "typical_housing": "Victorian villas in Wimbledon; Edwardian terraces in Tooting and Colliers Wood; 1930s semi-detached in Morden and Raynes Park; post-war flats in Mitcham.",
        "character": "Wimbledon is heavily conservation-controlled; outer Merton (Morden, Mitcham) is permissive.",
        "adjacent": ["wandsworth", "lambeth", "croydon", "sutton", "kingston-upon-thames"],
        "basement_policy": False,
    },
    "sutton": {
        "name": "Sutton",
        "council": "London Borough of Sutton",
        "planning_authority": "Sutton Council",
        "postcodes": "SM1, SM2, SM3, SM4, SM5, SM6, SM7",
        "population": 207_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 17,
        "notable_conservation": "Carshalton Village, Beddington Park, Cheam Village, Sutton Central",
        "typical_housing": "1930s semi-detached dominates; Edwardian terraces and villas in Sutton central; Victorian cottages in Carshalton; post-war in Hackbridge.",
        "character": "Outer south London suburban; generally permissive; Carshalton and Cheam conservation areas add heritage in pockets.",
        "adjacent": ["merton", "croydon", "kingston-upon-thames"],
        "basement_policy": False,
    },
    "croydon": {
        "name": "Croydon",
        "council": "London Borough of Croydon",
        "planning_authority": "Croydon Council",
        "postcodes": "CR0, CR2, CR5, CR7, CR8, CR9, SE19, SE20, SE25",
        "population": 390_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 24,
        "notable_conservation": "South Norwood, Crystal Palace, Old Coulsdon, Purley, Shirley Park",
        "typical_housing": "Victorian villas in Upper Norwood and Crystal Palace; Edwardian terraces in Thornton Heath and Selhurst; 1930s semi-detached in Purley and Coulsdon; post-war in Croydon central.",
        "character": "Large, mixed-density outer borough; permissive in outer areas; heritage controls in conservation pockets; major regeneration in central Croydon.",
        "adjacent": ["sutton", "merton", "lambeth", "bromley"],
        "basement_policy": False,
    },
    "bromley": {
        "name": "Bromley",
        "council": "London Borough of Bromley",
        "planning_authority": "Bromley Council",
        "postcodes": "BR1, BR2, BR3, BR4, BR5, BR6, BR7, BR8, SE6, SE9, SE12, SE20, SE26",
        "population": 332_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 48,
        "notable_conservation": "Bromley Town, Chislehurst, Beckenham, Keston, Bickley",
        "typical_housing": "Large 1930s detached and semi-detached in Chislehurst and Bickley; Edwardian in Beckenham; Victorian in Bromley town; Metropolitan Green Belt covers significant rural-fringe land.",
        "character": "Largest London borough by area; substantial Green Belt; conservation areas in most town centres; generally permissive elsewhere.",
        "adjacent": ["lewisham", "greenwich", "bexley", "croydon", "southwark"],
        "basement_policy": False,
    },
    "bexley": {
        "name": "Bexley",
        "council": "London Borough of Bexley",
        "planning_authority": "Bexley Council",
        "postcodes": "DA1, DA5, DA6, DA7, DA8, DA14, DA15, DA16, DA17, DA18",
        "population": 248_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 16,
        "notable_conservation": "Bexley Village, Old Bexley, Crayford, Welling",
        "typical_housing": "1930s semi-detached dominates; Victorian cottages in Bexley Village and Crayford; post-war estates in Thamesmead and Erith.",
        "character": "Outer south-east London suburban; very permissive planning environment; strong PD uptake for extensions and loft conversions.",
        "adjacent": ["greenwich", "bromley"],
        "basement_policy": False,
    },
    "havering": {
        "name": "Havering",
        "council": "London Borough of Havering",
        "planning_authority": "Havering Council",
        "postcodes": "RM1, RM2, RM3, RM4, RM5, RM7, RM11, RM12, RM13, RM14",
        "population": 263_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 15,
        "notable_conservation": "Romford Market, Upminster, Hornchurch, Rainham Village",
        "typical_housing": "1930s semi-detached dominates Hornchurch and Upminster; post-war in Harold Hill and Romford; Victorian in older Romford centre.",
        "character": "Outer east London; Metropolitan Green Belt covers north of the borough; permissive residential planning; strong PD use.",
        "adjacent": ["barking-and-dagenham", "redbridge"],
        "basement_policy": False,
    },
    "barking-and-dagenham": {
        "name": "Barking and Dagenham",
        "council": "London Borough of Barking and Dagenham",
        "planning_authority": "Barking and Dagenham Council",
        "postcodes": "IG11, RM6, RM8, RM9, RM10",
        "population": 218_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 9,
        "notable_conservation": "Becontree Estate (historic), Eastbury, Valence House",
        "typical_housing": "Becontree Estate (the world's largest council estate when built, 1920s-30s) dominates; post-war estates around Barking town; new-build riverside.",
        "character": "Major regeneration in Barking Riverside; mostly permissive planning outside conservation pockets.",
        "adjacent": ["havering", "redbridge", "newham"],
        "basement_policy": False,
    },
    "enfield": {
        "name": "Enfield",
        "council": "London Borough of Enfield",
        "planning_authority": "Enfield Council",
        "postcodes": "EN1, EN2, EN3, N9, N11, N13, N14, N18, N21",
        "population": 334_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 22,
        "notable_conservation": "Forty Hill, Enfield Town, Gentleman's Row, Winchmore Hill, Bush Hill Park",
        "typical_housing": "Edwardian villas in Palmers Green and Winchmore Hill; 1930s semi-detached in Southgate; Victorian terraces in Edmonton; Metropolitan Green Belt north of the borough.",
        "character": "Outer north London; Metropolitan Green Belt affects north; generally permissive elsewhere.",
        "adjacent": ["barnet", "haringey", "waltham-forest"],
        "basement_policy": False,
    },
    "brent": {
        "name": "Brent",
        "council": "London Borough of Brent",
        "planning_authority": "Brent Council",
        "postcodes": "NW2, NW6, NW9, NW10, HA0, HA9",
        "population": 340_000,
        "article_4": True,
        "article_4_notes": "Article 4 for HMO conversions in specific streets around Wembley and Harlesden.",
        "conservation_areas": 22,
        "notable_conservation": "Queen's Park, Mapesbury, Kensal Green, Harlesden, Sudbury Court",
        "typical_housing": "Edwardian villas in Queen's Park and Mapesbury; Victorian terraces in Kilburn and Harlesden; 1930s semi-detached in Wembley; post-war tower blocks in Church End.",
        "character": "Highly diverse borough; Queen's Park and Mapesbury are heritage-controlled; Wembley is a major regeneration hub.",
        "adjacent": ["barnet", "camden", "westminster", "kensington-and-chelsea", "hammersmith-and-fulham", "ealing", "harrow"],
        "basement_policy": False,
    },
    "harrow": {
        "name": "Harrow",
        "council": "London Borough of Harrow",
        "planning_authority": "Harrow Council",
        "postcodes": "HA1, HA2, HA3, HA5, HA7, HA8",
        "population": 261_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 29,
        "notable_conservation": "Harrow on the Hill, Pinner Village, Stanmore, Harrow Weald",
        "typical_housing": "1930s semi-detached dominates; Edwardian villas in Harrow on the Hill and Pinner; Metropolitan Green Belt in Stanmore and Harrow Weald; post-war flats around Harrow Central.",
        "character": "Outer north-west London suburban; Harrow on the Hill has exceptionally strict heritage controls; rest of borough permissive.",
        "adjacent": ["hillingdon", "barnet", "brent"],
        "basement_policy": False,
    },
    "hillingdon": {
        "name": "Hillingdon",
        "council": "London Borough of Hillingdon",
        "planning_authority": "Hillingdon Council",
        "postcodes": "HA4, HA5, HA6, UB3, UB4, UB7, UB8, UB9, UB10, UB11",
        "population": 306_000,
        "article_4": False,
        "article_4_notes": "",
        "conservation_areas": 29,
        "notable_conservation": "Uxbridge, Ruislip Village, Northwood, Harefield, Ickenham",
        "typical_housing": "1930s semi-detached dominates; Metropolitan Green Belt covers much of north Hillingdon; Victorian cottages in Uxbridge and Ruislip villages; post-war housing near Heathrow.",
        "character": "Largest outer west London borough; significant Green Belt; Heathrow noise contours affect planning decisions in Harmondsworth and Sipson.",
        "adjacent": ["harrow", "ealing", "hounslow"],
        "basement_policy": False,
    },
    "city-of-london": {
        "name": "City of London",
        "council": "City of London Corporation",
        "planning_authority": "City of London Corporation",
        "postcodes": "EC1, EC2, EC3, EC4",
        "population": 11_000,
        "article_4": True,
        "article_4_notes": "Multiple Article 4 Directions around office-to-residential, demolition, and shopfront changes.",
        "conservation_areas": 27,
        "notable_conservation": "Barbican, Smithfield, Fleet Street, Whitefriars, St Paul's",
        "typical_housing": "Very limited residential — Barbican Estate (listed post-war), Golden Lane Estate, modern luxury flats; overwhelmingly commercial.",
        "character": "Overwhelmingly commercial; residential planning extremely constrained; listed building density the highest of any London borough.",
        "adjacent": ["westminster", "camden", "islington", "hackney", "tower-hamlets", "southwark"],
        "basement_policy": False,
    },
}

# List of borough slugs in display order
BOROUGH_SLUGS = list(BOROUGHS.keys())


def borough_name(slug):
    return BOROUGHS[slug]["name"]


def adjacent_names(slug):
    """Return display names of adjacent boroughs."""
    return [BOROUGHS[a]["name"] for a in BOROUGHS[slug]["adjacent"] if a in BOROUGHS]
